### ISSUE TITLE
Whats the exact steps to compile this code 

### ISSUE THREAD

**Issue by Mohsannaeem** [canyalniz/CNN-Inference-Didactic#1]
Hy  ,I am finding CNN inference for  my FYP.  I run  weight_to_text.py file in anaconda but at "model.load_weights('weights_vanilla.h5') " this line of code i could not find weights_vanilla.h5 ...
Can you tell me the exact step to  compile and give a input and get output .Thanks

**Comment by canyalniz** [comment]
Greetings,

I am sorry it took this long for me to reply. Initially, for some reason, I didn't receive any notifications for this issue, and once I saw your question I was already preparing a much more detailed **README.md** and the documentation for this project. The answer to your question and a detail guide on how to use this framework are now in the repository. Please feel free to ask any other questions you may have.
