### ISSUE TITLE
IndexError: index 3 is out of bounds for axis 0 with size 3

### ISSUE THREAD

**Issue by Mohsannaeem** [canyalniz/CNN-Inference-Didactic#10]
Hi I am trying  generator.extract_weight(model) and then error comes
           IndexError: index 3 is out of bounds for axis 0 with size 3
![error](https://user-images.githubusercontent.com/26227899/67619568-a43de700-f816-11e9-9b3a-31b23557d63a.png)

**Comment by canyalniz** [comment]
Like I pointed out in #2 (and in the [README](https://github.com/canyalniz/CNN-Inference-Didactic/blob/master/README.md/#channels-first)) this library requires your Keras model to be channels first. You can configure your model in [a few different ways](https://stackoverflow.com/questions/46965047/channels-first-with-keras), the quickest is to just put `keras.backend.set_image_data_format('channels_first')` right after your imports. Also keep in mind that this line of code must be run before you even train the network.
