### ISSUE TITLE
Could not able to find the parameter of empty_Dense() and Flatten

### ISSUE THREAD

**Issue by Mohsannaeem** [canyalniz/CNN-Inference-Didactic#11]
Hy , I know this is not problem in your framework but you can guide me 
  I am just building model.c but could not configure Flatten dimension (Height,width and depth) and the other problem that i could not able to know empty_Dense() parameter (Number ,height,width and depth of kernal ) Can you guide me how to find this parameter ???Thanks in advance for your help...

**Comment by canyalniz** [comment]
Do you have a Keras model you are taking as reference?

**Comment by Mohsannaeem** [comment]
https://colab.research.google.com/drive/1p2VDUPNE4Mh2zyxY2MW464ZXzWVCNae8
This is my python code and  my c code  model is like that 

[model.txt](https://github.com/canyalniz/CNN-Inference-Didactic/files/3804672/model.txt)


I am aslo confused with the make_tensor parameter  and don't know how to find these parameter

**Comment by canyalniz** [comment]
Even though this model is not explicitly built using the Keras Sequential model, it has a sequential form. Therefore you can just call `generator.generate(model)` using **generator.py** to automatically get **model.c**. Which should turn out like this:
[model.txt](https://github.com/canyalniz/CNN-Inference-Didactic/files/3808117/model.txt)
